# Site settings
title: Client Name
email: dev@ocupop.com
url: "http://client_url.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code:


# Collections
collections:
  examples:
    output: true
    layout: default
    permalink: /examples/:path/

# defaults:
#   -
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false


plugins:
  - jekyll-sitemap
  # - jekyll-feed
  # - jekyll-lunr-js-search
  # - jekyll-archives
  # - jekyll-contentblocks


# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder